syntax ="proto3";

package currency;

option go_package = "github.com/varun-muthanna/products-api/protos/currency;currency";

service Currency{
    rpc GetRate(RateRequest) returns (RateResponse);
}

// defines the request 

message RateRequest{
    Currencies source=1;
    Currencies destination=2;
}

// define response 

message RateResponse{
    float rate=1;
}

//enum reprsenting the allowed currencies 

enum Currencies {
  EUR=0;
  USD=1;
  JPY=2;
  BGN=3;
  CZK=4;
  DKK=5;
  GBP=6;
  HUF=7;
  PLN=8;
  RON=9;
  SEK=10;
  CHF=11;
  ISK=12;
  NOK=13;
  HRK=14;
  RUB=15;
  TRY=16;
  AUD=17;
  BRL=18;
  CAD=19;
  CNY=20;
  HKD=21;
  IDR=22;
  ILS=23;
  INR=24;
  KRW=25;
  MXN=26;
  MYR=27;
  NZD=28;
  PHP=29;
  SGD=30;
  THB=31;
  ZAR=32;
}






